### ISSUE TITLE
Bug: Moderation queue

### ISSUE THREAD

**Issue by mitchwd** [Dweez/sms-twitter-wall#3]
Sometimes the moderation queue appears and then disappears. It works for a few refreshes, and then disappears for hours! But I can't seem to work out why. Any ideas?

**Comment by Dweez** [comment]
For hours ?!
Never had this problem ...
Without seeing exactly what happens it'll be difficult to debug but perhaps a lock on the database file ?
I do not really know if it would cause an error or if the wall becomes silent in this case ...
